baseurl      = "https://qualiaq.github.io/"
title        = "Krzysztof Dolega"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Philosopher"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Krzysztof Dolega"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "krys_dolega"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    weight = 100
    name       = "About"
    url        = "/about"
    
  [[menu.main]]
    identifier = "papers"
    weight = 200
    name       = "Papers"
    url        = "/papers"
    
  [[menu.main]]
    identifier = "talks"
    weight = 300
    name       = "Talks"
    url        = "/talks"
  
  [[menu.main]]
    identifier = "blog"
    weight = 400
    name       = "Blog"
    url        = "/posts"
    
 [[menu.main]]
    identifier = "outreach"
    name       = "Outreach"
    url        = "/outreach"
